In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [3]:
arr2d = np.array([[1, 2, 3],
              [4, 5, 6]])
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [4]:
zeros = np.zeros(10)
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
ones = np.ones((3, 3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [6]:
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
arr = np.array([[1, 2], [3, 4]])
print(arr.ndim)

2


In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)

(2, 3)


In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.size)

6


In [11]:
arr = np.arange(1, 13).reshape(3, 4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [12]:
arr = np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3)
print(arr)

[[1 2 3]
 [4 5 6]]


In [13]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[2])

30


In [14]:
arr = np.array([10, 20, 30, 40, 50, 60])
print(arr[2:6])

[30 40 50 60]


In [15]:
arr = np.array([[1, 2, 3],
              [4, 5, 6]])
print(arr[1, 2])

6


In [16]:
arr = np.array([1, 2, 3, 4, 5])
print(arr * 2)

[ 2  4  6  8 10]


In [17]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)

[5 7 9]


In [18]:
arr = np.array([1, 2, 3, 4, 5])
print(arr ** 2)

[ 1  4  9 16 25]


In [21]:
arr = np.array([3, 1, 7, 2, 9, 4])
print('max :', arr.max())
print('min :', arr.min())

max : 9
min : 1


In [25]:
arr = np.array([3, 1, 7, 2, 9, 5])
print(arr.argmax())

4


In [26]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.mean())

3.0


In [27]:
arr = np.random.randint(1, 51, size=5)
print(arr)

[ 5 41 22 13 46]
